name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  build_and_security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t pen-test .

      - name: Run Docker container
        run: docker run -d -p 3030:3030 --name pen-test-container pen-test

      - name: Run ZAP Security Scan
        id: zap_scan
        run: |
          result=$(docker run -t --network="host" ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3030)
          echo "$result"
          fail_count=$(echo "$result" | grep -c 'FAIL')
          echo "::set-output name=fail_count::$fail_count"

      - name: Stop and remove Docker container
        run: docker stop pen-test-container && docker rm pen-test-container

      - name: Check ZAP scan results and set output
        if: steps.zap_scan.outputs.fail_count > 0
        run: exit 1
