name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  build_and_security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ZAP Security Scan
        run: make zap-scan

      - name: Stop and remove Docker container
        run: docker stop pen-test-container && docker rm pen-test-container || true
